services:
  - type: web
    name: flotaseguraapp
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flet run main.py --host 0.0.0.0 --port $PORT"
    envVars:
      - key: FLET_VERSION
        value: 0.28.3

static_files:
  - path: /assets
    url_prefix: /assets