# Usar la imagen base de Python que ya estábamos usando
FROM mcr.microsoft.com/devcontainers/python:0-3.10

# Instalar una herramienta de ejemplo para demostrar que funciona
RUN apt-get update && apt-get install -y cowsay